### ISSUE TITLE
Getting rid of PhantomData

### ISSUE THREAD

**Issue by hardliner66** [dtolnay/ghost#16]
Could this be used to somehow get rid of using PhantomData?

so we could do something like:
```rust
struct Test<T> {
  i: i32,
  s: String,
}
```

**Comment by dtolnay** [comment]
Yes that would be possible to implement. It is not the goal of this crate though.

**Comment by hardliner66** [comment]
@dtolnay Was this implemented or did you just close the issue? I'm just a bit confused by the `closed this as completed`.
