### ISSUE TITLE
Support phantom void enum

### ISSUE THREAD

**Issue by L-as** [dtolnay/ghost#2]
Title.

**Comment by dtolnay** [comment]
I'm not sure what you mean. Could you give an example of the enum use case you have in mind?

**Comment by L-as** [comment]
Sorry for late reply, here's an example:
```rust
enum MyEnum<T> {}
```
Today this won't work since `T` isn't used. You can't use `PhantomData` here as easily, since you'd *need* to create a variant, which you don't want.

**Comment by dtolnay** [comment]
It is not currently implemented but the same technique would work. I would be prepared to consider a PR adding support for zero-variant enums.

**Comment by dtolnay** [comment]
Upon revisiting this, I think I'll leave this functionality to a different crate.
