### ISSUE TITLE
Avoid unimplementing auto traits on phantom struct

### ISSUE THREAD

**Issue by alecmocatta** [dtolnay/ghost#5]
This line: https://github.com/dtolnay/ghost/blob/1035d84d5bd7e5988483ecb75fb8b71486e59801/src/variance.rs#L48 could be relaxed to `quote!(fn() -> #phantom)` to avoid unimplementing auto traits on the phantom struct and also [affecting the drop check](https://doc.rust-lang.org/nomicon/phantom-data.html#table-of-phantomdata-patterns).

Phantom structs should probably always be `Send`, `Sync` and so on, I would have thought? But right now they only are if all covariant arguments also are.

**Comment by dtolnay** [comment]
I think the current implementation is behaving correctly. The autotrait impls for `core::marker::PhantomData` are also conditional.
https://doc.rust-lang.org/1.60.0/std/marker/struct.PhantomData.html#impl-Send

<br>

![Screenshot from 2022-04-24 16-12-09](https://user-images.githubusercontent.com/1940490/165000609-4fae5faa-cf5f-471e-b637-1418f1115327.png)
